site_name: MISSION I/O
site_description: Mission modules documentation
site_author: Natarajan Ganapathi
site_url: https://mission-io.github.io/docs

# Repository
repo_name: mission-io/mission.docs
repo_url: https://github.com/mission-io/mission.docs
edit_uri: ""

# Copyright
copyright: "Copyright &copy; 2018 - 2019 mission.io"

# Configuration
theme:
  name: "material"

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png
  # logo: 'img/logo.jpg'
  logo:
    icon: "cloud"

# Customization
extra:
  social:
    # - type: globe
    #   link: http://www.mission.io
    - type: github-alt
      link: https://github.com/mission-io
    # - type: twitter
    #   link: https://twitter.com/mission-io
    - type: linkedin
      link: https://www.linkedin.com/company/mission-io

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home:
      - Overview: home/overview.md
      - Get started: home/get-started.md
      - Setup: home/setup.md
      - Architecture: home/architecture.md
      - Create REST API: home/create-rest-api.md
      - Create Rest API for RDMS database: home/create-rest-api-for-rdbms-database.md
      - API Testing and code coverage: home/api-testing-and-code-coverage.md
      # - MongoDB: home/mongodb.md
      # - Scheduler: home/scheduler.md
      - Open API 3.0: home/open-api-3.0.md
      - Containaraization: home/containaraization.md
      - CLI Commands: home/cli-commands.md
      - Microservice with mission I/O: home/microservice-with-mission-io.md
      - Contributing: home/contributing.md
      # - Release notes: 
          # - mission cli: release-notes/mission.cli.md
          # - mission common: release-notes/mission.common.md
          # - mission api: release-notes/mission.api.md
          # - mission core: release-notes/mission.core.md
          # - mission scheduler: release-notes/mission.scheduler.md
      - Comments and Feedback: home/comments-and-feedback.md
      - License: home/license.md
  - Mission modules:
      - mission common: mission-modules/mission.common.md
      - mission api: mission-modules/mission.api.md
      - mission core: mission-modules/mission.core.md
      - mission cli: mission-modules/mission.cli.md
      - mission scheduler: mission-modules/mission.scheduler.md
      - mission mongodb: mission-modules/mission.mongodb.md
  - Functional modules:
      - Pdf Maker: functional-modules/pdf-maker.md
      - reference-value: functional-modules/reference-value.md
      - sequence-number: functional-modules/sequence-number.md
  - Features:
      - "": features/features.md
  - Team:
      - Core: team/core-team.md
      - Contributors: team/contributors.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
